apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-ingress-route-certificate
  namespace: nginx-test
spec:
  # Secret names are always required.
  secretName: nginx-test-certificate-secret
  issuerRef:
    name: cloudflare-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - nginx-test.kube-dev.echopossum.com
