ports:
  web:
    redirections:
      entryPoint:
        to: websecure
        scheme: https
ingressRoute:
  dashboard:
    enabled: true
    entryPoints: [web, websecure]
    matchRule: Host(`traefik.kube-dev.echopossum.com`)
    tls:
      secretName: traefik-dashboard-secret
